on: 
  push:
    branches:
    - devops
name: deploy Amazon
jobs:
  deploy:
    name: deploy odoo14 addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'frank@frank-HP-ProBook-450-G8-Notebook-PC'
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST_AMAZON }} >> ~/.ssh/known_hosts
    
    - name: Deploy with rsync
      run: |
        rm -rf ~/odoo14/addons/*
        rsync -avz ./* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST_AMAZON }}:~/odoo14/addons/
        sudo docker-compose -f ~/odoo14/docker-compose.yml restart
