on: 
  push:
    branches:
    - master
name: deploy repo SUPI
jobs:
  deploy:
    name: deploy odoo14 addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: deploy pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
        ADDONS_PATH: "/home/fjvigil/web/docker/odoo/odoo-14-docker-compose/addons"
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 10s
        first_ssh: |
          rm -rf $ADDONS_PATH/*
          ls -la  \necho $WELCOME 
        scp: |
          './test/*' => $ADDONS_PATH/
          
        last_ssh: |
          echo $LASTSSH 