on: 
  push:
    branches:
    - master
name: deploy repo SUPI
jobs:
  deploy:
    name: deploy odoo14 addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      env:
        WOELCOME: "localhost"
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        scp_source: ./*
        scp_target: /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/addons/
        before_script: |
          cd /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/
          echo ${{ secrets.SERVER_PASSWORD }} 
          sudo -S -k docker-compose kill 
          chmod -R 775 /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/addons 
          rm -rf /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/addons/*
        after_script: |
          cd /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/
          echo ${{ secrets.SERVER_PASSWORD }} 
          sudo -S -k docker-compose restart