on: 
  push:
    branches:
    - master
name: deploy repo SUPI
jobs:
  deploy:
    name: deploy odoo14 addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      run: |
        cd /home/fjvigil/web/docker/odoo/odoo-14-docker-compose/addons/
        ls -la
      with:
        owner: 'fjvigil89'
        repository: 'ages_supi'

    